/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm';
import { DateTime } from 'luxon';

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'email',
    'emailVerifiedAt',
    'fullName',
    'id',
    'image',
    'password',
    'role',
    'updatedAt',
    'username',
  ] as const;
  $columns = UserSchema.$columns;
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime;
  @column()
  declare email: string;
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null;
  @column()
  declare fullName: string | null;
  @column({ isPrimary: true })
  declare id: number;
  @column()
  declare image: string | null;
  @column({ serializeAs: null })
  declare password: string;
  @column()
  declare role: string;
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null;
  @column()
  declare username: string;
}
