/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BookChapterAudioSchema extends BaseModel {
  static $columns = [
    'audioPath',
    'bookId',
    'chapterIndex',
    'chunkCount',
    'createdAt',
    'durationMs',
    'errorCode',
    'errorMessage',
    'id',
    'status',
    'textHash',
    'timingWords',
    'updatedAt',
    'voiceHash',
  ] as const
  $columns = BookChapterAudioSchema.$columns
  @column()
  declare audioPath: string | null
  @column()
  declare bookId: number
  @column()
  declare chapterIndex: number
  @column()
  declare chunkCount: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare durationMs: number | null
  @column()
  declare errorCode: string | null
  @column()
  declare errorMessage: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: string
  @column()
  declare textHash: string
  @column()
  declare timingWords: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare voiceHash: string
}

export class BookChapterSchema extends BaseModel {
  static $columns = [
    'bookId',
    'chapterIndex',
    'content',
    'createdAt',
    'id',
    'title',
    'updatedAt',
  ] as const
  $columns = BookChapterSchema.$columns
  @column()
  declare bookId: number
  @column()
  declare chapterIndex: number
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class BookChatSchema extends BaseModel {
  static $columns = ['bookId', 'content', 'createdAt', 'id', 'role', 'updatedAt', 'userId'] as const
  $columns = BookChatSchema.$columns
  @column()
  declare bookId: number
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class BookLevelSchema extends BaseModel {
  static $columns = [
    'code',
    'createdAt',
    'description',
    'id',
    'isActive',
    'maxWords',
    'minWords',
    'name',
    'sortOrder',
    'updatedAt',
  ] as const
  $columns = BookLevelSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare maxWords: number | null
  @column()
  declare minWords: number | null
  @column()
  declare name: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class BookProcessingRunLogSchema extends BaseModel {
  static $columns = [
    'bookId',
    'createdAt',
    'currentStep',
    'durationMs',
    'errorCode',
    'errorMessage',
    'finishedAt',
    'id',
    'jobType',
    'metadata',
    'progress',
    'startedAt',
    'status',
    'updatedAt',
  ] as const
  $columns = BookProcessingRunLogSchema.$columns
  @column()
  declare bookId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currentStep: string | null
  @column()
  declare durationMs: bigint | number | null
  @column()
  declare errorCode: string | null
  @column()
  declare errorMessage: string | null
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare jobType: string
  @column()
  declare metadata: any | null
  @column()
  declare progress: number
  @column.dateTime()
  declare startedAt: DateTime
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class BookProcessingStepLogSchema extends BaseModel {
  static $columns = [
    'bookId',
    'createdAt',
    'durationMs',
    'errorCode',
    'errorMessage',
    'finishedAt',
    'id',
    'inputHash',
    'itemKey',
    'outputRef',
    'runLogId',
    'startedAt',
    'status',
    'stepKey',
    'updatedAt',
  ] as const
  $columns = BookProcessingStepLogSchema.$columns
  @column()
  declare bookId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare durationMs: bigint | number | null
  @column()
  declare errorCode: string | null
  @column()
  declare errorMessage: string | null
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare inputHash: string | null
  @column()
  declare itemKey: string | null
  @column()
  declare outputRef: any | null
  @column()
  declare runLogId: number
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare stepKey: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class BookReadProgressSchema extends BaseModel {
  static $columns = ['bookId', 'createdAt', 'id', 'progress', 'updatedAt', 'userId'] as const
  $columns = BookReadProgressSchema.$columns
  @column()
  declare bookId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare progress: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class BookTagSchema extends BaseModel {
  static $columns = ['bookId', 'createdAt', 'tagId', 'updatedAt'] as const
  $columns = BookTagSchema.$columns
  @column({ isPrimary: true })
  declare bookId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare tagId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class BookVocabularySchema extends BaseModel {
  static $columns = [
    'bookId',
    'createdAt',
    'dictionaryEntryId',
    'frequency',
    'id',
    'lemma',
    'sentence',
    'updatedAt',
    'word',
  ] as const
  $columns = BookVocabularySchema.$columns
  @column()
  declare bookId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dictionaryEntryId: bigint | number | null
  @column()
  declare frequency: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lemma: string
  @column()
  declare sentence: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare word: string
}

export class BookSchema extends BaseModel {
  static $columns = [
    'audioGeneratedAt',
    'audioStatus',
    'audioTiming',
    'audioUrl',
    'author',
    'bookHash',
    'contentHash',
    'createdAt',
    'createdBy',
    'description',
    'id',
    'isPublished',
    'levelClassifiedAt',
    'levelClassifiedBy',
    'levelId',
    'processingError',
    'processingProgress',
    'processingStep',
    'rawFileExt',
    'rawFileHash',
    'rawFileName',
    'rawFilePath',
    'rawFileSize',
    'readingTime',
    'source',
    'status',
    'title',
    'updatedAt',
    'vocabularyStatus',
    'wordCount',
  ] as const
  $columns = BookSchema.$columns
  @column.dateTime()
  declare audioGeneratedAt: DateTime | null
  @column()
  declare audioStatus: string | null
  @column()
  declare audioTiming: any | null
  @column()
  declare audioUrl: string | null
  @column()
  declare author: string | null
  @column()
  declare bookHash: string | null
  @column()
  declare contentHash: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isPublished: boolean
  @column.dateTime()
  declare levelClassifiedAt: DateTime | null
  @column()
  declare levelClassifiedBy: string
  @column()
  declare levelId: number
  @column()
  declare processingError: string | null
  @column()
  declare processingProgress: number
  @column()
  declare processingStep: string | null
  @column()
  declare rawFileExt: string | null
  @column()
  declare rawFileHash: string | null
  @column()
  declare rawFileName: string | null
  @column()
  declare rawFilePath: string | null
  @column()
  declare rawFileSize: bigint | number | null
  @column()
  declare readingTime: number
  @column()
  declare source: string
  @column()
  declare status: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare vocabularyStatus: string | null
  @column()
  declare wordCount: number
}

export class ChapterTranslationSchema extends BaseModel {
  static $columns = [
    'chapterId',
    'contentHash',
    'createdAt',
    'createdByUserId',
    'errorMessage',
    'id',
    'metadata',
    'model',
    'provider',
    'resultJson',
    'sourceLanguage',
    'status',
    'targetLanguage',
    'updatedAt',
  ] as const
  $columns = ChapterTranslationSchema.$columns
  @column()
  declare chapterId: number
  @column()
  declare contentHash: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number | null
  @column()
  declare errorMessage: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare metadata: any | null
  @column()
  declare model: string | null
  @column()
  declare provider: string | null
  @column()
  declare resultJson: any | null
  @column()
  declare sourceLanguage: string
  @column()
  declare status: string
  @column()
  declare targetLanguage: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DictionaryEntrySchema extends BaseModel {
  static $columns = [
    'articleExamples',
    'createdAt',
    'id',
    'localizationLanguage',
    'meanings',
    'metaSource',
    'phonetic',
    'phonetics',
    'sourceLanguage',
    'updatedAt',
    'word',
  ] as const
  $columns = DictionaryEntrySchema.$columns
  @column()
  declare articleExamples: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare localizationLanguage: string
  @column()
  declare meanings: any
  @column()
  declare metaSource: string
  @column()
  declare phonetic: string | null
  @column()
  declare phonetics: any
  @column()
  declare sourceLanguage: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare word: string
}

export class LearningRecordSchema extends BaseModel {
  static $columns = ['createdAt', 'date', 'id', 'learningDays', 'updatedAt', 'userId'] as const
  $columns = LearningRecordSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare learningDays: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class SystemConfigSchema extends BaseModel {
  static $columns = [
    'aiApiKey',
    'aiBaseUrl',
    'aiModelName',
    'createdAt',
    'id',
    'updatedAt',
  ] as const
  $columns = SystemConfigSchema.$columns
  @column()
  declare aiApiKey: string | null
  @column()
  declare aiBaseUrl: string | null
  @column()
  declare aiModelName: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TagSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'slug'] as const
  $columns = TagSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
}

export class UserConfigSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'englishVariant',
    'id',
    'learningInitCompleted',
    'nativeLanguage',
    'targetLanguage',
    'updatedAt',
    'userId',
    'vocabularyLevel',
  ] as const
  $columns = UserConfigSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare englishVariant: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare learningInitCompleted: boolean | null
  @column()
  declare nativeLanguage: string | null
  @column()
  declare targetLanguage: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare vocabularyLevel: string | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'avatar',
    'createdAt',
    'email',
    'fullName',
    'id',
    'isAdmin',
    'password',
    'provider',
    'providerId',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column()
  declare avatar: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isAdmin: boolean
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare provider: string | null
  @column()
  declare providerId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
